### ISSUE TITLE
F-Droid version cannot fetch data

### ISSUE THREAD

**Issue by xenotropic** [vbresan/WeatherForecastUSA#3]
The title basically says it all, I have internet connectivity, I'm in California, I tried both by GPS and by entering a zip code and in both cases the app says that it cannot download data. 

If you can't reproduce, let me know if there's additional information I can provide. 
![Screenshot_20240119-123834_Weather Forecast USA](https://github.com/vbresan/WeatherForecastUSA/assets/4050617/f10ed92b-ae8b-4e8c-b776-d00f885e38b1)

**Comment by vbresan** [comment]
@xenotropic I have just tried with the zip code from your screenshot and got the weather forecast. Are you still experiencing the same issue?

![Screenshot_20240120-063438_Weather Forecast USA](https://github.com/vbresan/WeatherForecastUSA/assets/288855/7e35fc84-3c38-4565-b153-e7ef0825df61)

**Comment by vbresan** [comment]
@xenotropic Please try the latest version 4.0.1. I believe that the previous version had some problems with connection retries. Unless you still can't fetch the weather data, I will close this issue.
